### ISSUE TITLE
Custom Claims Not Supported - With URL Namespaces - Auth0, etc. specifications

### ISSUE THREAD

**Issue by aicglabs** [smallrye/smallrye-jwt#289] opened 2020-07-22 22:35 UTC
There appears to be logic in [https://github.com/smallrye/smallrye-jwt/blob/ba7197e550865770d32fb2890e6ebd488e9534b7/implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParser.java](url) that we believe is preventing namespaced claims from being accepted as the alternate to the groups claim.

Attempting to implement Auth0, which only allows custom claims with namespaces, the use of the small-rye application property, **smallrye.jwt.path.groups**,  useless in this needed scenario.

The Auth0 specification is that custom claims must be namespace prefixed, for example, the claim for "**userdetails**" would need to be created in the Auth0 IDM as **"http://mysite.com/claims/userdetails"**.  Thus retrieving said custom claim would require:

JsonWebToken jwt;
System.out.println(jwt.getClaimNames().toString());

//output of above 
[sub, aud, azp, permissions, raw_token, scope, iss, groups, http://mysite.com/claims/userdetails, exp, iat]

System.out.println( jwt.getClaim("http://mysite.com/claims/userdetails").toString()) );
//output
["SpecialCustomer", "FireCustomer"]

The expected functionality for smallrye-jwt propery smallrye.jwt.path.groups is for this to accept any available claim as the groups claim so the standard RolesBased annotation security can be applied, for example, 
...
@Path("/secured-area")
@RolesAllowed({"FireCustomer", "Administrators"})
....

Using current release with quarkus in testing we found that namepaced claims in the format of "http://.../claim" using the above are not accepted, resulting in a Null value passed into the resulting AuthContextInfo object.

We have tested on single claim names such as "scope" as a claim just for testing purposes and that does work.

Any assistance here to be able to accept URL namespaced claims would be helpful.

**Comment by MikeEdgar** [comment] 2020-07-23 00:42
@aicglabs - try putting the property value in quotes. I.e.

`smallrye.jwt.path.groups="http://mysite.com/claims/userdetails"`

**Comment by sberyozkin** [comment] 2020-07-23 09:55
From the [documentation](https://github.com/smallrye/smallrye-jwt/blob/master/doc/modules/ROOT/pages/configuration.adoc) of this property: `Use double quotes with the namespace qualified claims.`  
It is also mentioned [here](https://github.com/smallrye/smallrye-jwt/blob/master/implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java#L228).

**Comment by aicglabs** [comment] 2020-07-23 15:04
Thanks for the response. That's a negative.

We've reviewed the documentation, and have just now triple checked your suggestion. It does not work, thus the issue.
We believe the reg-ex in the aforementioned class ([https://github.com/smallrye/smallrye-jwt/blob/ba7197e550865770d32fb2890e6ebd488e9534b7/implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParser.java](https://github.com/smallrye/smallrye-jwt/blob/ba7197e550865770d32fb2890e6ebd488e9534b7/implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParser.java)) is stripping out the slashes of the URL namepspace and rendering any entry on the property as Null in the small-rye AuthContextInfo.

I'm not sure if it is the regex or where else the issue resides,
[    private static final Pattern CLAIM_PATH_PATTERN = Pattern.compile("\\/(?=(?:(?:[^\"]*\"){2})*[^\"]*$)"); ](https://github.com/smallrye/smallrye-jwt/blob/ba7197e550865770d32fb2890e6ebd488e9534b7/implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParser.java#L54) ,
we just know that regardless of double-quotes, single-quotes, or even escaping the slashes it doesn't seem to work correctly for us.

**Comment by MikeEdgar** [comment] 2020-07-24 00:35
@aicglabs - the String in the example doesn't have quotes enclosing the value, such as:

`String claimPath = "\"http://mysite.com/claims/userdetails\"";`

You've done the same in your properties file?

**Comment by sberyozkin** [comment] 2020-07-24 13:33
@aicglabs We've had several Quarkus users confirming it works, and indeed, as @MikeEdgar pointed out, your test configuration is not correct. See for example https://github.com/smallrye/smallrye-jwt/blob/master/testsuite/basic/src/test/java/io/smallrye/jwt/TestTokenWithGroupsPath.java#L69, there should be another similar test around somewhere. IMHO this issue is invalid.
Thanks

**Comment by sberyozkin** [comment] 2020-07-24 13:34
@aicglabs Here is the test resource: https://github.com/smallrye/smallrye-jwt/blob/master/testsuite/basic/src/test/resources/TokenGroupsPath.json#L18

**Comment by aicglabs** [comment] 2020-07-24 15:56
@sberyozkin @MikeEdgar Thanks for your inputs, it took both of your insights to prove and disprove this. I have it working now

I re-ran the test resource posted by @sberyozkin and noticed the only test scenario provides only one path on the namespace URL (i.e.: https://idp/groups). I hadn't tried this before as we were following the best practice Auth0 specification of two path extensions on the namespace URL (i.e. ../claims/<claim_name>) - so this difference of **http://mysite.com/userdetails** vs. **http://mysite.com/claims/userdetails** respectfully is the issue at hand.  

Potentially an additional test should be created so that the test suite has https://idp/groups and https://idp/claims/groups, etc. 

The solution for now was to:

1. modify the existing IDM (e.g. Auth0) claim output to comply with http://mysite.com/userdetails instead of http://mysite.com/claims/userdetails, referring to my original example above.  (We were not sure Auth0 allowed this as potentially some other IDM's restrict it, but we were happy it allowed the flexibility away from their documented best practice recommendation.)
2. updated the quarkus application.properties file to reflect the above, smallrye.jwt.path.groups="http://mysite.com/userdetails"

This works and complies with what we needed to accomplish.

Again, a very valid issue, and we recommend either updating the docs or adding the additional test.  I'll be happy to create a pull request if the team is receptive to that.  

We can close this issue.

BTW, an amazing project guys keep up the great work! Hopefully we can contribute in an even more meaningful way in the future.

**Comment by sberyozkin** [comment] 2020-07-24 16:22
Hi @aicglabs thanks, can you please follow up with another test which will resolve this issue ? I actually did do the test locally awhile back when dealing with a Quarkus user query but forgot to add it here.

**Comment by sberyozkin** [comment] 2020-07-26 11:52
@aicglabs having said it all, let me close this issue as it is not a bug, sorry for the noise. But indeed, your PRs to improve the tests/docs etc will be very welcome :-)
Cheers

**Closed by sberyozkin** 2020-07-26 11:52 UTC
