### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by vankofalcon** [smallrye/smallrye-jwt#184] opened 2020-02-19 14:15 UTC
Where is the project documentation? I can't find it on the official web site like the messaging docs https://smallrye.io/smallrye-reactive-messaging/
Where I can find the full list of configuration options?

**Comment by sberyozkin** [comment] 2020-02-20 16:53
@vankofalcon I agree, but let me close this issue as a duplicate of #106.

I will get the configuration properties documented for the next release

**Comment by sberyozkin** [comment] 2020-02-20 16:55
@vankofalcon Most of the properties are listed [here](https://quarkus.io/guides/security-jwt#additional-smallrye-jwt-configuration). But they will be documented here as well...

**Closed** 2020-02-20 16:55 UTC
